<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39279" started-at="2017-12-18T10:33:19Z" finished-at="2017-12-18T10:33:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39279" started-at="2017-12-18T10:33:19Z" finished-at="2017-12-18T10:33:59Z">
      <class name="Scenario_Component.company_profile">
        <test-method status="PASS" signature="Report_extent()[pri:0, instance:Scenario_Component.company_profile@598067a5]" name="Report_extent" is-config="true" duration-ms="264" started-at="2017-12-18T16:03:19Z" finished-at="2017-12-18T16:03:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report_extent -->
        <test-method status="FAIL" signature="test_Case1()[pri:0, instance:Scenario_Component.company_profile@598067a5]" name="test_Case1" is-config="true" duration-ms="0" started-at="2017-12-18T16:03:19Z" finished-at="2017-12-18T16:03:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at Scenario_Component.Primary_tests.test_Case1(Primary_tests.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Case1 -->
        <test-method status="SKIP" signature="test_case1()[pri:0, instance:Scenario_Component.company_profile@598067a5]" name="test_case1" duration-ms="2" started-at="2017-12-18T16:03:59Z" finished-at="2017-12-18T16:03:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case1 -->
      </class> <!-- Scenario_Component.company_profile -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
