<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38759" started-at="2017-12-29T12:50:48Z" finished-at="2017-12-29T12:51:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38759" started-at="2017-12-29T12:50:48Z" finished-at="2017-12-29T12:51:26Z">
      <class name="Scenario_Component.FC_001_companyProfile">
        <test-method status="PASS" signature="Report_extent()[pri:0, instance:Scenario_Component.FC_001_companyProfile@553f17c]" name="Report_extent" is-config="true" duration-ms="232" started-at="2017-12-29T18:20:47Z" finished-at="2017-12-29T18:20:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report_extent -->
        <test-method status="PASS" signature="primary_check()[pri:0, instance:Scenario_Component.FC_001_companyProfile@553f17c]" name="primary_check" is-config="true" duration-ms="37933" started-at="2017-12-29T18:20:48Z" finished-at="2017-12-29T18:21:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- primary_check -->
        <test-method status="PASS" signature="Onload_Load_Check()[pri:0, instance:Scenario_Component.FC_001_companyProfile@553f17c]" name="Onload_Load_Check" duration-ms="784" started-at="2017-12-29T18:21:26Z" finished-at="2017-12-29T18:21:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Onload_Load_Check -->
        <test-method status="FAIL" signature="stop_process()[pri:0, instance:Scenario_Component.FC_001_companyProfile@553f17c]" name="stop_process" is-config="true" duration-ms="0" started-at="2017-12-29T18:21:26Z" finished-at="2017-12-29T18:21:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at Scenario_Component.FC_001_companyProfile.stop_process(FC_001_companyProfile.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1021)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stop_process -->
      </class> <!-- Scenario_Component.FC_001_companyProfile -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
